#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.scr39
    set site_3_0 $base.scr40
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#
    menu .pop38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop38" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 834x451+418+179
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr39 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr39" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr39.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable objs
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr40 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr40" "Scrolledlistbox2" vTcl:WidgetProc "Toplevel1" 1

    $top.scr40.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -listvariable obss
    canvas $top.can42 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 191 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 271 
    vTcl:DefineAlias "$top.can42" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can43 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 201 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 271 
    vTcl:DefineAlias "$top.can43" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Button 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Button 
    vTcl:DefineAlias "$top.but46" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Button 
    vTcl:DefineAlias "$top.but47" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Button 
    vTcl:DefineAlias "$top.but48" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Button 
    vTcl:DefineAlias "$top.but49" "Button5" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex50 \
        -background white -font TkTextFont -foreground black -height 124 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 206 \
        -wrap word 
    .top37.tex50 configure -font TkTextFont
    .top37.tex50 insert end text
    vTcl:DefineAlias "$top.tex50" "Text1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.scr39 \
        -in $top -x 20 -y 10 -width 266 -relwidth 0 -height 378 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.scr40 \
        -in $top -x 300 -y 180 -width 226 -relwidth 0 -height 208 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.can42 \
        -in $top -x 550 -y 240 -width 271 -relwidth 0 -height 191 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.can43 \
        -in $top -x 550 -y 30 -width 271 -relwidth 0 -height 201 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent44 \
        -in $top -x 330 -y 20 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 510 -y 20 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 20 -y 410 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 110 -y 410 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 200 -y 410 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 300 -y 410 -anchor nw -bordermode ignore 
    place $top.tex50 \
        -in $top -x 310 -y 50 -width 206 -relwidth 0 -height 124 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

