#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.5
#    Oct 16, 2019 08:51:43 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global objs
    objs = tk.StringVar()
    global combobox
    combobox = tk.StringVar()

def About():
    print('main1_support.About')
    sys.stdout.flush()

def AddObj():
    print('main1_support.AddObj')
    sys.stdout.flush()

def AddObs():
    print('main1_support.AddObs')
    sys.stdout.flush()

def DelObj():
    print('main1_support.DelObj')
    sys.stdout.flush()

def DelObs():
    print('main1_support.DelObs')
    sys.stdout.flush()

def EditObj():
    print('main1_support.EditObj')
    sys.stdout.flush()

def EditObs():
    print('main1_support.EditObs')
    sys.stdout.flush()

def Exit():
    print('main1_support.Exit')
    sys.stdout.flush()

def NewFile():
    print('main1_support.NewFile')
    sys.stdout.flush()

def NowTime():
    print('main1_support.NowTime')
    sys.stdout.flush()

def OpenFile():
    print('main1_support.OpenFile')
    sys.stdout.flush()

def SaveFile():
    print('main1_support.SaveFile')
    sys.stdout.flush()

def Settings():
    print('main1_support.Settings')
    sys.stdout.flush()

def ShowImg():
    print('main1_support.ShowImg')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import main1
    main1.vp_start_gui()




