#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Oct 19, 2019 05:41:25 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global objs
    objs = StringVar()
    global combobox
    combobox = StringVar()

def About():
    print('main3_support.About')
    sys.stdout.flush()

def AddObj():
    print('main3_support.AddObj')
    sys.stdout.flush()

def AddObs():
    print('main3_support.AddObs')
    sys.stdout.flush()

def DelObj():
    print('main3_support.DelObj')
    sys.stdout.flush()

def DelObs():
    print('main3_support.DelObs')
    sys.stdout.flush()

def EditObj():
    print('main3_support.EditObj')
    sys.stdout.flush()

def EditObs():
    print('main3_support.EditObs')
    sys.stdout.flush()

def Exit():
    print('main3_support.Exit')
    sys.stdout.flush()

def NewFile():
    print('main3_support.NewFile')
    sys.stdout.flush()

def NowTime():
    print('main3_support.NowTime')
    sys.stdout.flush()

def OpenFile():
    print('main3_support.OpenFile')
    sys.stdout.flush()

def SaveFile():
    print('main3_support.SaveFile')
    sys.stdout.flush()

def Settings():
    print('main3_support.Settings')
    sys.stdout.flush()

def ShowImg():
    print('main3_support.ShowImg')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import main3
    main3.vp_start_gui()


