#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 368x450+429+172
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Name 
    vTcl:DefineAlias "$top.lab38" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent39 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent39" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text RA 
    vTcl:DefineAlias "$top.lab40" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent41 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent41" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Add 
    vTcl:DefineAlias "$top.but42" "Button1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text DEC 
    vTcl:DefineAlias "$top.lab43" "Label3" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Mag 
    vTcl:DefineAlias "$top.lab45" "Label4" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent46" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Size 
    vTcl:DefineAlias "$top.lab47" "Label5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Type 
    vTcl:DefineAlias "$top.lab49" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent50" "Entry6" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Notes 
    vTcl:DefineAlias "$top.lab51" "Label7" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex52 \
        -background white -font TkTextFont -foreground black -height 4 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 10 \
        -wrap word 
    .top37.tex52 configure -font TkTextFont
    .top37.tex52 insert end text
    vTcl:DefineAlias "$top.tex52" "Text1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent38 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent38" "Entry7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but39 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Detect 
    vTcl:DefineAlias "$top.but39" "Button2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -background {#d9d9d9} -foreground {#000000} -text Constellation 
    vTcl:DefineAlias "$top.lab41" "Label8" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 30 -y 30 -anchor nw -bordermode ignore 
    place $top.ent39 \
        -in $top -x 110 -y 30 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 50 -y 70 -anchor nw -bordermode ignore 
    place $top.ent41 \
        -in $top -x 140 -y 80 -anchor nw -bordermode ignore 
    place $top.but42 \
        -in $top -x 220 -y 410 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 40 -y 110 -anchor nw -bordermode ignore 
    place $top.ent44 \
        -in $top -x 130 -y 110 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 40 -y 180 -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 130 -y 190 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 40 -y 240 -anchor nw -bordermode ignore 
    place $top.ent48 \
        -in $top -x 110 -y 240 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 50 -y 280 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 120 -y 280 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 50 -y 320 -anchor nw -bordermode ignore 
    place $top.tex52 \
        -in $top -x 120 -y 320 -anchor nw -bordermode ignore 
    place $top.ent38 \
        -in $top -x 140 -y 150 -width 106 -relwidth 0 -height 23 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but39 \
        -in $top -x 270 -y 150 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 30 -y 150 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

