#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 446x331+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab38 \
        -background {#d9d9d9} -foreground {#000000} -text Observer 
    vTcl:DefineAlias "$top.lab38" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent39 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent39" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -background {#d9d9d9} -foreground {#000000} -text Date 
    vTcl:DefineAlias "$top.lab40" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -background {#d9d9d9} -foreground {#000000} -text Site 
    vTcl:DefineAlias "$top.lab41" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab42 \
        -background {#d9d9d9} -foreground {#000000} -text Instrument 
    vTcl:DefineAlias "$top.lab42" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -background {#d9d9d9} -foreground {#000000} -text Object 
    vTcl:DefineAlias "$top.lab43" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -background {#d9d9d9} -foreground {#000000} -text Image 
    vTcl:DefineAlias "$top.lab44" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent45" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text add 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text save 
    vTcl:DefineAlias "$top.but47" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo48 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo48" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo49 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo49" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo50 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo50" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo51 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "TCombobox4" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 50 -y 30 -anchor nw -bordermode ignore 
    place $top.ent39 \
        -in $top -x 120 -y 80 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 60 -y 80 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 60 -y 120 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 50 -y 160 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 60 -y 200 -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 60 -y 250 -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 130 -y 250 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 320 -y 250 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 170 -y 290 -anchor nw -bordermode ignore 
    place $top.tCo48 \
        -in $top -x 130 -y 30 -anchor nw -bordermode ignore 
    place $top.tCo49 \
        -in $top -x 130 -y 120 -anchor nw -bordermode ignore 
    place $top.tCo50 \
        -in $top -x 160 -y 160 -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 140 -y 200 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

