#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Oct 07, 2019 04:22:43 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import observation_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    observation_support.set_Tk_var()
    top = New_Toplevel (root)
    observation_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    observation_support.set_Tk_var()
    top = New_Toplevel (w)
    observation_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("446x331+650+150")
        top.title("New Toplevel")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.11, rely=0.09, height=21, width=63)
        self.Label1.configure(text='''Observer''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.27, rely=0.24,height=23, relwidth=0.37)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Label2 = Label(top)
        self.Label2.place(relx=0.13, rely=0.24, height=21, width=35)
        self.Label2.configure(text='''Date''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.13, rely=0.36, height=21, width=29)
        self.Label3.configure(text='''Site''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.11, rely=0.48, height=21, width=75)
        self.Label4.configure(text='''Instrument''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.13, rely=0.6, height=21, width=46)
        self.Label5.configure(text='''Object''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.13, rely=0.76, height=21, width=45)
        self.Label6.configure(text='''Image''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.29, rely=0.76,height=23, relwidth=0.37)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.72, rely=0.76, height=29, width=50)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''add''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.38, rely=0.88, height=29, width=57)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''save''')

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(relx=0.29, rely=0.09, relheight=0.06, relwidth=0.4)

        self.TCombobox1.configure(textvariable=observation_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.TCombobox2 = ttk.Combobox(top)
        self.TCombobox2.place(relx=0.29, rely=0.36, relheight=0.06, relwidth=0.4)

        self.TCombobox2.configure(textvariable=observation_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.TCombobox3 = ttk.Combobox(top)
        self.TCombobox3.place(relx=0.36, rely=0.48, relheight=0.06, relwidth=0.4)

        self.TCombobox3.configure(textvariable=observation_support.combobox)
        self.TCombobox3.configure(takefocus="")

        self.TCombobox4 = ttk.Combobox(top)
        self.TCombobox4.place(relx=0.31, rely=0.6, relheight=0.06, relwidth=0.4)
        self.TCombobox4.configure(textvariable=observation_support.combobox)
        self.TCombobox4.configure(takefocus="")






if __name__ == '__main__':
    vp_start_gui()



