#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Oct 07, 2019 04:33:21 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import settings_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    settings_support.set_Tk_var()
    top = New_Toplevel (root)
    settings_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    settings_support.set_Tk_var()
    top = New_Toplevel (w)
    settings_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("530x260+445+225")
        top.title("New Toplevel")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.04, rely=0.12, height=21, width=111)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''default observer''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.04, rely=0.27, height=21, width=78)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''default site''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.04, rely=0.46, height=21, width=118)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''default technique''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.04, rely=0.65, height=21, width=78)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''image path''')

        self.Radiobutton1 = Radiobutton(top)
        self.Radiobutton1.place(relx=0.23, rely=0.65, relheight=0.09
                , relwidth=0.15)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''original''')

        self.Radiobutton2 = Radiobutton(top)
        self.Radiobutton2.place(relx=0.42, rely=0.65, relheight=0.09
                , relwidth=0.12)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''copy''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.26, rely=0.85, height=29, width=57)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''save''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.62, rely=0.12, height=29, width=50)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''add''')

        self.Button2_1 = Button(top)
        self.Button2_1.place(relx=0.62, rely=0.27, height=29, width=50)
        self.Button2_1.configure(activebackground="#d9d9d9")
        self.Button2_1.configure(text='''add''')

        self.Button2_2 = Button(top)
        self.Button2_2.place(relx=0.62, rely=0.42, height=29, width=50)
        self.Button2_2.configure(activebackground="#d9d9d9")
        self.Button2_2.configure(text='''add''')

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(relx=0.26, rely=0.12, relheight=0.08
                , relwidth=0.33)
        self.TCombobox1.configure(textvariable=settings_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.TCombobox2 = ttk.Combobox(top)
        self.TCombobox2.place(relx=0.26, rely=0.27, relheight=0.08
                , relwidth=0.33)
        self.TCombobox2.configure(textvariable=settings_support.combobox)
        self.TCombobox2.configure(takefocus="")

        self.TCombobox3 = ttk.Combobox(top)
        self.TCombobox3.place(relx=0.26, rely=0.46, relheight=0.08
                , relwidth=0.33)
        self.TCombobox3.configure(textvariable=settings_support.combobox)
        self.TCombobox3.configure(takefocus="")

        self.Button2_1 = Button(top)
        self.Button2_1.place(relx=0.75, rely=0.12, height=29, width=50)
        self.Button2_1.configure(activebackground="#d9d9d9")
        self.Button2_1.configure(text='''edit''')

        self.Button2_2 = Button(top)
        self.Button2_2.place(relx=0.75, rely=0.27, height=29, width=50)
        self.Button2_2.configure(activebackground="#d9d9d9")
        self.Button2_2.configure(text='''edit''')

        self.Button2_2 = Button(top)
        self.Button2_2.place(relx=0.75, rely=0.42, height=29, width=50)
        self.Button2_2.configure(activebackground="#d9d9d9")
        self.Button2_2.configure(text='''edit''')

        self.Button2_2 = Button(top)
        self.Button2_2.place(relx=0.89, rely=0.12, height=29, width=50)
        self.Button2_2.configure(activebackground="#d9d9d9")
        self.Button2_2.configure(text='''delete''')

        self.Button2_3 = Button(top)
        self.Button2_3.place(relx=0.89, rely=0.27, height=29, width=50)
        self.Button2_3.configure(activebackground="#d9d9d9")
        self.Button2_3.configure(text='''delete''')

        self.Button2_3 = Button(top)
        self.Button2_3.place(relx=0.89, rely=0.42, height=29, width=50)
        self.Button2_3.configure(activebackground="#d9d9d9")
        self.Button2_3.configure(text='''delete''')






if __name__ == '__main__':
    vp_start_gui()



