#############################################################################
# Generated by PAGE version 4.14
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 530x260+445+225
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1585 870
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab38 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {default observer} 
    vTcl:DefineAlias "$top.lab38" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {default site} 
    vTcl:DefineAlias "$top.lab39" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {default technique} 
    vTcl:DefineAlias "$top.lab40" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {image path} 
    vTcl:DefineAlias "$top.lab41" "Label4" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text original -variable {} 
    vTcl:DefineAlias "$top.rad42" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $top.rad43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text copy -variable {} 
    vTcl:DefineAlias "$top.rad43" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text save 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text add 
    vTcl:DefineAlias "$top.but47" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text add 
    vTcl:DefineAlias "$top.but48" "Button2_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text add 
    vTcl:DefineAlias "$top.but49" "Button2_2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo50 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo50" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo51 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "TCombobox2" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo52 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo52" "TCombobox3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text edit 
    vTcl:DefineAlias "$top.but50" "Button2_1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text edit 
    vTcl:DefineAlias "$top.but52" "Button2_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text edit 
    vTcl:DefineAlias "$top.but53" "Button2_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but54 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text delete 
    vTcl:DefineAlias "$top.but54" "Button2_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but55 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text delete 
    vTcl:DefineAlias "$top.but55" "Button2_3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text delete 
    vTcl:DefineAlias "$top.but56" "Button2_3" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab38 \
        -in $top -x 20 -y 30 -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 20 -y 70 -anchor nw -bordermode ignore 
    place $top.lab40 \
        -in $top -x 20 -y 120 -anchor nw -bordermode ignore 
    place $top.lab41 \
        -in $top -x 20 -y 170 -anchor nw -bordermode ignore 
    place $top.rad42 \
        -in $top -x 120 -y 170 -anchor nw -bordermode ignore 
    place $top.rad43 \
        -in $top -x 220 -y 170 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 140 -y 220 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 330 -y 30 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 330 -y 70 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but49 \
        -in $top -x 330 -y 110 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.tCo50 \
        -in $top -x 140 -y 30 -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 140 -y 70 -anchor nw -bordermode ignore 
    place $top.tCo52 \
        -in $top -x 140 -y 120 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 400 -y 30 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but52 \
        -in $top -x 400 -y 70 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but53 \
        -in $top -x 400 -y 110 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but54 \
        -in $top -x 470 -y 30 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but55 \
        -in $top -x 470 -y 70 -width 50 -height 29 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x 470 -y 110 -width 50 -height 29 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

