#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Oct 07, 2019 04:31:51 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import site_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    site_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    site_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("335x317+403+194")
        top.title("New Toplevel")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.09, rely=0.13, height=21, width=43)
        self.Label1.configure(text='''Name''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.33, rely=0.13,height=23, relwidth=0.5)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Label2 = Label(top)
        self.Label2.place(relx=0.12, rely=0.32, height=21, width=57)
        self.Label2.configure(text='''Latitude''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.39, rely=0.32,height=23, relwidth=0.5)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Label3 = Label(top)
        self.Label3.place(relx=0.12, rely=0.5, height=21, width=68)
        self.Label3.configure(text='''Longitude''')

        self.Entry3 = Entry(top)
        self.Entry3.place(relx=0.42, rely=0.5,height=23, relwidth=0.5)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")

        self.Label4 = Label(top)
        self.Label4.place(relx=0.09, rely=0.69, height=21, width=65)
        self.Label4.configure(text='''Elevation''')

        self.Entry4 = Entry(top)
        self.Entry4.place(relx=0.36, rely=0.69,height=23, relwidth=0.5)
        self.Entry4.configure(background="white")
        self.Entry4.configure(font="TkFixedFont")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.42, rely=0.85, height=29, width=58)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Save''')






if __name__ == '__main__':
    vp_start_gui()



